add variable to enable oms_agent
cloudcommons/terraform-azure-kubernetes pull request #7
Opened 2020-02-24 08:49 UTC by sergiomcalzada

Add a variable to enable the Azure Monitor

2020-02-24 18:45 UTC, sesispla requested changes
Please adjust the description and default values. Thanks!!

2020-02-24 18:45 UTC, sesispla commented on variables.tf
> +  description = "(Required) The Log Analytics Workspace id when the OMS should store logs."
Please change it to "(Optional)"

2020-02-24 18:45 UTC, sesispla commented on variables.tf
> +  default     = false
Please change the default value to "null" (without quotes)

2020-02-24 21:59 UTC, sergiomcalzada commented on variables.tf
> +  description = "(Required) The Log Analytics Workspace id when the OMS should store logs."
done

2020-02-24 21:59 UTC, sergiomcalzada commented on variables.tf
> +  default     = false
done

2020-02-25 11:20 UTC, sesispla approved these changes
Perfect, thank you!!

2020-02-25 11:21 UTC, merged