Added aad-pod-identity support
cloudcommons/terraform-azure-kubernetes pull request #9
Opened 2020-02-24 17:38 UTC by sergiomcalzada

2020-02-24 18:33 UTC, sesispla commented
@sergiomcalzada I found that some of the elements you created via kubectl are: 
* Deployment
* DaemonSet
* ClusterRole
* ClusterRoleBinding
* ServiceAccount

It is true that terraform don't provide (or at least I don't know) a way to create Kubernetes CRDs

Please consider turning all the YAML files into terraform files that can be properly tracked and managed by terraform.

2020-02-24 18:44 UTC, sesispla requested changes
Having a closer look to it, this looks like a terraform module itself :)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +  namespace: default
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/service_account.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +  verbs: ["get", "list", "watch"]
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/cluster_role.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +  apiGroup: rbac.authorization.k8s.io
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/cluster_role_binding.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +        beta.kubernetes.io/os: linux
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/daemonset.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +---
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/service_account.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +---
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/cluster_role.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +---
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/cluster_role_binding.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity-rbac.yml
> +        beta.kubernetes.io/os: linux
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/deployment.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity.yml
> +        beta.kubernetes.io/os: linux
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/deployment.html)

2020-02-24 18:44 UTC, sesispla commented on aad-pod-identity.yml
> +        beta.kubernetes.io/os: linux
Please use this [terraform resource](https://www.terraform.io/docs/providers/kubernetes/r/daemonset.html)

2020-02-24 18:44 UTC, sesispla commented on .gitignore
> +/vars/secret.tfvars
Could you please confirm what this file is?

2020-02-24 21:56 UTC, sergiomcalzada commented
The yml file comes from an [Azure Github](https://github.com/Azure/aad-pod-identity) and I don't want to split them for easy update... but... Checking the releases they also provide a helm package (that is not documented)... Will try it and check

2020-02-29 11:07 UTC, sesispla commented
@sergiomcalzada  Using your inputs here, I'm closing this in favour of the newly implemented [cloudcommons/terraform-kubernetes-aad-pod-identity-rbac](https://github.com/cloudcommons/terraform-kubernetes-aad-pod-identity-rbac). 

This will be made available in the generator with cloudcommons/generator-cli#11 but you can start using the [module](https://registry.terraform.io/modules/cloudcommons/aad-pod-identity-rbac/kubernetes/0.1.0) today

2020-02-29 11:07 UTC, closed without merging